name: Build & Deploy MkDocs site


# ── DONNER LES DROITS D’ÉCRITURE ─────────────────────────────
permissions:
  contents: write    # autorise le push de commits
  pages:    write    # autorise le déploiement GitHub Pages
  id-token: write    # nécessaire pour certains tokens OIDC
# ───────────────────────────────────────────────────────────────


on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material jinja2

      - name: Initialize database
        run: python3 init_db.py

      - name: Generate dashboard markdown
        run: python3 generate_dashboard.py

      - name: Build site
        run: mkdocs build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages
