name: Build & Deploy MkDocs site

# Déclenchement sur les commits dans master
on:
  push:
    branches: [ master ]        # ← CORRECTION ICI :contentReference[oaicite:1]{index=1}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 2.1 Récupérer le code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2.2 Initialiser SQLite (crée dossier + table alerts)
      - name: Initialize database
        run: python init_db.py    # doit contenir CREATE TABLE IF NOT EXISTS :contentReference[oaicite:2]{index=2}

      # 2.3 Préparer Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 2.4 Installer MkDocs et Jinja2
      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material jinja2

      # 2.5 Générer les .md via Jinja
      - name: Generate dashboard markdown
        run: python generate_dashboard.py

      # 2.6 Builder le site statique
      - name: Build site
        run: mkdocs build

      # 2.7 Déployer sur gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3    # Action officielle pour Pages :contentReference[oaicite:3]{index=3}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages             # spécifie la branche de déploiement :contentReference[oaicite:4]{index=4}
